src/Entity/Objet.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ObjetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ObjetRepository::class)]
#[ApiResource(normalizationContext: ['groupe' => ['product']])] //AJOUTER API RESOURCE ICI
class Objet
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'objets')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $Proprietaire = null;

    #[ORM\Column(length: 255)]
    private ?string $nomObjet = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Image = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    /**
     * @var Collection<int, Emprunt>
     */
    #[ORM\OneToMany(targetEntity: Emprunt::class, mappedBy: 'objet')]
    private Collection $emprunts;

    #[ORM\ManyToOne(inversedBy: 'objets')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categorie $categorie = null;

    public function __construct()
    {
        $this->emprunts = new ArrayCollection();
    }

    #[ORM\ManyToOne(inversedBy: 'objet')]
    #[ORM\JoinColumn(nullable: false)]

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProprietaire(): ?User
    {
        return $this->Proprietaire;
    }

    public function setProprietaire(?User $Proprietaire): static
    {
        $this->Proprietaire = $Proprietaire;

        return $this;
    }

    public function getNomObjet(): ?string
    {
        return $this->nomObjet;
    }

    public function setNomObjet(string $nomObjet): static
    {
        $this->nomObjet = $nomObjet;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): static
    {
        $this->Image = $Image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Emprunt>
     */
    public function getEmprunts(): Collection
    {
        return $this->emprunts;
    }

    public function addEmprunt(Emprunt $emprunt): static
    {
        if (!$this->emprunts->contains($emprunt)) {
            $this->emprunts->add($emprunt);
            $emprunt->setObjet($this);
        }

        return $this;
    }

    public function removeEmprunt(Emprunt $emprunt): static
    {
        if ($this->emprunts->removeElement($emprunt)) {
            // set the owning side to null (unless already changed)
            if ($emprunt->getObjet() === $this) {
                $emprunt->setObjet(null);
            }
        }

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }
}

src/Form/ObjetType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use App\Entity\Objet;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ObjetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nomObjet')
            ->add('Image')
            ->add('description')
            ->add('Proprietaire', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'id',
            ])
            ->add('categorie', EntityType::class, [
                'class' => Categorie::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Objet::class,
        ]);
    }
}

src/Controller/ObjetController.php
<?php

namespace App\Controller;

use App\Entity\Objet;
use App\Form\ObjetType;
use App\Repository\ObjetRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/objet')]
final class ObjetController extends AbstractController
{
    #[Route(name: 'app_objet_index', methods: ['GET'])]
    public function index(ObjetRepository $objetRepository): Response
    {
        return $this->render('objet/index.html.twig', [
            'objets' => $objetRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_objet_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $objet = new Objet();
        $form = $this->createForm(ObjetType::class, $objet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($objet);
            $entityManager->flush();

            return $this->redirectToRoute('app_objet_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('objet/new.html.twig', [
            'objet' => $objet,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_objet_show', methods: ['GET'])]
    public function show(Objet $objet): Response
    {
        return $this->render('objet/show.html.twig', [
            'objet' => $objet,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_objet_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Objet $objet, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ObjetType::class, $objet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_objet_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('objet/edit.html.twig', [
            'objet' => $objet,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_objet_delete', methods: ['POST'])]
    public function delete(Request $request, Objet $objet, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$objet->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($objet);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_objet_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/objet/_delete_form.html.twig
<form method="post" action="{{ path('app_objet_delete', {'id': objet.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ objet.id) }}">
    <button class="btn">Delete</button>
</form>

templates/objet/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/objet/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Objet{% endblock %}

{% block body %}
    <h1>Edit Objet</h1>

    {{ include('objet/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_objet_index') }}">back to list</a>

    {{ include('objet/_delete_form.html.twig') }}
{% endblock %}

templates/objet/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Objet index{% endblock %}

{% block body %}
    <h1>Objet index</h1>

        {% for objet in objets %}
            <div class="card" style="width: 18rem;">
                <img src={{ asset('imgObjet/' ~ objet.image) }} class="card-img-top" alt="...">
                <div class="card-body">
                <h1>{{ objet.nomObjet }}</h1>
                <p class="card-text">{{ objet.description }}</p>
                </div>
                <button class="btn"><a href={{ path('app_objet_show', {'id': objet.id}) }}>voir l'objet</a></button>
            </div>

        {% else %}
            <h1>aucun objet trouver</h1>
        {% endfor %}
       

    {% if is_granted('ROLE_USER')%}
            <a href="{{ path('app_objet_new') }}">Create new</a>
        {% endif %}
{% endblock %}

templates/objet/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Objet{% endblock %}

{% block body %}
    <h1>Create new Objet</h1>

    {{ include('objet/_form.html.twig') }}

    <a href="{{ path('app_objet_index') }}">back to list</a>
{% endblock %}

templates/objet/objetItem.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ObjetITEM!{% endblock %}


{% block body %}


<div class = "objetDescribe">
    <h1></h1>
    <div class = "objetDescribe__img">
        <img src="{{ asset('imgObjet/' ~ objetItem.image )}}" alt="">
    </div>

</div>
{% endblock %}

templates/objet/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Objet{% endblock %}

{% block body %}
    <h1>Objet</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ objet.id }}</td>
            </tr>
            <tr>
                <th>NomObjet</th>
                <td>{{ objet.nomObjet }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ objet.Image }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ objet.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_objet_index') }}">back to list</a>

    <a href="{{ path('app_objet_edit', {'id': objet.id}) }}">edit</a>

    {{ include('objet/_delete_form.html.twig') }}
{% endblock %}